### ISSUE TITLE
After adding product from wishlist to checkout, product are not moved from wishlist.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#12]
**Bug Name -**  After adding product from wishlist to checkout, product are not moved from wishlist.
**Area Path -** Front End
**Status -** New
**Woo Commerce Version -** 5.1.0
**WordPress Version -** 5.7
**Plugin Version -** 1.0.0
**Description -**

[https://drive.google.com/file/d/1fe6tnTQGtDJ8iZMV37JrBig6c0QdzTAk/view?usp=sharing](url)

**Comment by Stuti-Cedcoss** [comment]
Fixed
