### ISSUE TITLE
When you delete the plugin alert message are displayed for delete its data but no data are deleted.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#24]
**Bug Name -** When you delete the plugin alert message are displayed for delete its data but no data are deleted.
**Area Path -** Front End
**Status -** New
**Woo Commerce Version -** 5.1.0
**WordPress Version -** 5.7
**Plugin Version -** 1.0.0
**Description -**

https://drive.google.com/file/d/1m0NxcWED66SMw470mYMFSlSL-QnAgK15/view?usp=sharing

**Comment by Stuti-Cedcoss** [comment]
Fixed
