### ISSUE TITLE
Your friends button are not working.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#27]
**Bug Name -** Your friends button are not working.
**Area Path -** Front End
**Status -** New
**Woo Commerce Version -** 5.1.0
**WordPress Version -** 5.7
**Plugin Version -** 1.0.0
**Description -**

![your friends](https://user-images.githubusercontent.com/76723393/111863846-dc9e1200-8983-11eb-8c5a-f7a2442fa834.png)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
