### ISSUE TITLE
QA issues.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#29]
**Bug Name -**  QA issues.
**Area Path -** Back End.
**Status -** New
**Woo Commerce Version -** 5.1.0
**WordPress Version -** 5.7
**Plugin Version -** 1.0.0
**Description -**

Update -  

* Requires at least:   		
* Tested up to: 			5.7  
* WC requires at least:    	  
* WC tested up to: 			5.1.0

* License:           GPL-2.0+
* License URI:       http://www.gnu.org/licenses/gpl-2.0.txt

- Please update the @package name and test domain according to the plugin name in the whole plugin. It must be the same.

-Use .onclick() rather than .click()
 admin/js/wishlist-for-woo-admin.js   65 290

-Use .onbind() rather than .bind()
admin/js/select2.min.js
admin/js/swal.js
admin/js/wishlist-for-woo-admin.js
public/js/wishlist-pushy-sdk.js

- PHPcs 
[mwb-wishlist-for-woocommerce.docx](https://github.com/Makewebbetter/mwb-wishlist-for-woocommerce/files/6181564/mwb-wishlist-for-woocommerce.docx)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
