### ISSUE TITLE
I install v1.0.2 but it showes v1.0.0 and it demands update.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#31]
**Bug Name -**  I install v1.0.2 but it showes v1.0.0 and it demands update.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.3.0
**WordPress Version -** 5.7.2
**Plugin Version -** 1.0.2
**Description -**

![image](https://user-images.githubusercontent.com/76723393/120806015-fc48dd80-c563-11eb-9bab-f5779b83e4ff.png)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
okkk
