### ISSUE TITLE
After installing the plugin may warnings are displaying.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#32]
**Bug Name -**  After installing may warnings are displaying.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.3.0
**WordPress Version -** 5.7.2
**Plugin Version -** 1.0.2
**Description -**

![image](https://user-images.githubusercontent.com/76723393/120955559-44881b80-c76f-11eb-8521-7670ca056c37.png)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
