### ISSUE TITLE
In the shop page more warnings are displaying in the shop page.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#34]
**Bug Name -** In the shop page more warnings are displaying in the shop page.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.3.0
**WordPress Version -** 5.7.2
**Plugin Version -** 1.0.2
**Description -**

![image](https://user-images.githubusercontent.com/76723393/120956385-10adf580-c771-11eb-95a9-b0546d61aea3.png)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
