### ISSUE TITLE
Wishlist are not working.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#35]
**Bug Name -** Wishlist are not working.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.3.0
**WordPress Version -** 5.7.2
**Plugin Version -** 1.0.2
**Description -**

https://www.awesomescreenshot.com/video/4029614?key=5e3c7dfd7f2ed70528a31019beab408c

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
