### ISSUE TITLE
Add to wish list button are also not working.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#36]
**Bug Name -** Add to wish list button are also not working.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.3.0
**WordPress Version -** 5.7.2
**Plugin Version -** 1.0.2
**Description -**

![image](https://user-images.githubusercontent.com/76723393/120957611-a0ed3a00-c773-11eb-8d78-57f00998650b.png)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
