### ISSUE TITLE
Product is added on wishlist but in wishlisk its not displayed.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#37]
**Bug Name -** Product is added on wishlist but in wishlisk its not displayed.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.4.1
**WordPress Version -** 5.7.2
**Plugin Version -** 1.0.2
**Description -**

https://www.awesomescreenshot.com/video/4094990?key=31d89690ba5f68d4f2a956cf1aac851f

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
