### ISSUE TITLE
Product is added on wishlist but in wishlist its not displayed. ( on PHP vs- 8.0.0 )

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#38]
**Bug Name -** Product is added on wishlist but in wishlist its not displayed.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.4.1
**WordPress Version -** 5.7.2
**Plugin Version -** 1.0.2
**Description -**

![image](https://user-images.githubusercontent.com/76723393/121691020-28280e00-cae4-11eb-8bb8-1e70332e34a8.png)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
