### ISSUE TITLE
Buy now button is not working.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#39]
**Bug Name -** Buy now button is not working.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.4.1
**WordPress Version -** 5.7.2
**Plugin Version -** 1.0.2
**Description -**

![image](https://user-images.githubusercontent.com/76723393/121693890-2c095f80-cae7-11eb-8a34-6d24fef58d2b.png)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
