### ISSUE TITLE
Add to wishlist button having some issues.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#42]
**Bug Name -**  Add to wishlist button having some issues.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.4.1
**WordPress Version -** 5.7.2
**Plugin Version -** 1.0.2
**Description -**

https://www.awesomescreenshot.com/video/4096714?key=488ced11235b3fdb86620baec4223539

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
