### ISSUE TITLE
Update the version on front end.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#44]
**Bug Name -**  Update the version on front end.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.4.1
**WordPress Version -** 5.7.2
**Plugin Version -** 1.0.2
**Description -**

![image](https://user-images.githubusercontent.com/76723393/122343329-37cfa880-cf63-11eb-8e02-c844c6d6e639.png)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
