### ISSUE TITLE
Add to wishlist button comes in center.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#45]
**Bug Name -** Add to wishlist button comes in center.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.4.1
**WordPress Version -** 5.7.2
**Plugin Version -** 1.0.2
**Description -**

![image](https://user-images.githubusercontent.com/76723393/122393572-a0824980-cf92-11eb-9a27-4d0a0efaf69f.png)

![image](https://user-images.githubusercontent.com/76723393/122393009-0cb07d80-cf92-11eb-9563-6cf0c9ce0e08.png)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
