### ISSUE TITLE
QA Issues

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#46]
**Bug Name -** QA Issues
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.4.1
**WordPress Version -** 5.7.2
**Plugin Version -** 1.0.2
**Description -**

Commented Code-
- admin/css/makewebbetter-onboarding-admin.css 363-366
- public/js/ultimate-wishlist-for-woocommerce-public.js 25 
- public/partials/ultimate-wishlist-for-woocommerce-shortcode-view.php 103-104

Tested up to 
- WC 5.4.1
- WP 5.7.2

Avoid touching the database directly ( $wpdb->insert )
- includes/class-ultimate-wishlist-for-woocommerce-crud-manager.php 95, 105, 108, 148, 158, 161 

PHPCS Issues-

[ultimate-wishlist-for-woocommerce.docx](https://github.com/Makewebbetter/ultimate-wishlist-for-woocommerce/files/6674449/ultimate-wishlist-for-woocommerce.docx)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
