### ISSUE TITLE
Warning are here.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#49]
**Bug Name -** Warning are here.
**Area Path -** When you open the plugin on back end.
**Status -** New
**Woo Commerce Version -** 5.5.1
**WordPress Version -** 5.7.2
**PHP Version -** 8.0.0
**Plugin Version -** 1.0.2
**Description -**

https://www.awesomescreenshot.com/image/10730070?key=8007d94a7a19edf5801496a2b45e1dfa

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
