### ISSUE TITLE
After finishing 30 days of trial license have issue and also license is not required.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#52]
**Bug Name -** After finishing 30 days of trial license have issue and also license is not required.
**Area Path -** When you open the plugin on back end.
**Status -** New
**Woo Commerce Version -** 5.5.1
**WordPress Version -** 5.7.2
**PHP Version -** 8.0.0
**Plugin Version -** 1.0.2
**Description -**

After finishing 30 days of trial license have an issue.

![image](https://user-images.githubusercontent.com/76723393/125887646-c5b1ac9f-2367-45d9-9a22-36a15b2d63a3.png)

and this is ORG plugin so the license is not required.

![image](https://user-images.githubusercontent.com/76723393/125889045-e03c9f8f-56c5-4cb5-93ee-239deb4ed963.png)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
