### ISSUE TITLE
Save setting button is missed.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#53]
**Bug Name -** Save setting button is missed.
**Area Path -** When you open the plugin on back end.
**Status -** New
**Woo Commerce Version -** 5.5.1
**WordPress Version -** 5.7.2
**PHP Version -** 8.0.0
**Plugin Version -** 1.0.2
**Description -**

![image](https://user-images.githubusercontent.com/76723393/125889623-ba9a5969-fa3a-4b98-a967-0388694975dd.png)

**Comment by Stuti-Cedcoss** [comment]
This tab displays the features which we will provide in the pro plugin so these settings need not to be saved.

**Comment by AnuraktSachan-CEDCOSS** [comment]
So please provide the tag of "PRO" & provide the "save setting" button but it becomes disabled.

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
