### ISSUE TITLE
For "Add to wishlist button" some settings are not useful so please hide. 

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#55]
**Bug Name -** For "Add to wishlist button" some settings are not useful so please hide. 
**Area Path -** When you open the plugin on back end.
**Status -** New
**Woo Commerce Version -** 5.5.1
**WordPress Version -** 5.7.2
**PHP Version -** 8.0.0
**Plugin Version -** 1.0.2
**Description -**

![image](https://user-images.githubusercontent.com/76723393/125893738-6ceaaf74-5240-4e59-8574-a63ce62c8726.png)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
