### ISSUE TITLE
Issue in adding related products in variable products.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#57]
**Bug Name -** Issue in adding related products in variable products.
**Area Path -** When you open the plugin on back end.
**Status -** New
**Woo Commerce Version -** 5.5.1
**WordPress Version -** 5.7.2
**PHP Version -** 8.0.0
**Plugin Version -** 1.0.2
**Description -**

![image](https://user-images.githubusercontent.com/76723393/125913394-5ed31fb6-7840-44fe-b9e7-7fb5cf5407fd.png)

![image](https://user-images.githubusercontent.com/76723393/125913884-3bf4f303-185f-4f1e-b7db-4beeafc33931.png)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok but now this issue

![image](https://user-images.githubusercontent.com/76723393/126734595-c19478b5-48fd-4700-ab47-6b213f7c09b0.png)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
