### ISSUE TITLE
Icon over product image are not working on demo setup.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#60]
**Bug Name -** Icon over product image are not working on demo setup.
**Area Path -** When you open the plugin on back end.
**Status -** New
**Woo Commerce Version -** 5.5.1
**WordPress Version -** 5.7.2
**PHP Version -** 8.0.0
**Plugin Version -** 1.0.2
**Description -**

https://www.awesomescreenshot.com/video/4511021?key=b8e29be99073c8c6b48d8d6283c27d2c

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok but please check this console

![image](https://user-images.githubusercontent.com/76723393/126736103-d23928c7-3377-4060-8e04-97c04c16d99e.png)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
