### ISSUE TITLE
Add to wishlist button issue on demo setup.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#62]
**Bug Name -** Add to wishlist button issue on demo setup.
**Area Path -** When you open the plugin on back end.
**Status -** New
**Woo Commerce Version -** 5.5.1
**WordPress Version -** 5.7.2
**PHP Version -** 8.0.0
**Plugin Version -** 1.0.2
**Description -**

https://www.awesomescreenshot.com/video/4511117?key=dba193e548e7d4f483d7b752033fb827

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
