### ISSUE TITLE
After activation plugin demands for update.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#63]
**Bug Name -** After activation plugin demands for update.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.5.1
**WordPress Version -** 5.7.2
**PHP Version -** 8.0.0
**Plugin Version -** 1.0.2
**Description -**

![image](https://user-images.githubusercontent.com/76723393/126022972-2eba6dfb-65d7-4d12-82b7-273b1bec7395.png)

![image](https://user-images.githubusercontent.com/76723393/126022927-7a7c9aea-ae51-481e-b5b0-5ed970f7e0d3.png)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
