### ISSUE TITLE
QA Issues

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#64]
**Bug Name -** QA Issues
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.5.2
**WordPress Version -** 5.8
**PHP Version -** 8.0.0
**Plugin Version -** 1.0.2
**Description -**

**Remove this ( extra files )-**
admin/css/ultimate-wishlist-for-woocommerce-admin-global.css
assets/src/front-end/js/custom.js
common/css/ultimate-wishlist-for-woocommerce-common.css suspect
assets/src/back-end/image/banner.jpg

**Commented Code-**
admin/partials/ultimate-wishlist-for-woocommerce-license.php 17
common/js/ultimate-wishlist-for-woocommerce-common.js 14-22
common/class-ultimate-wishlist-for-woocommerce-common.php 118
onboarding/js/ultimate-wishlist-for-woocommerce-onboarding.js 127-129
public/js/ultimate-wishlist-for-woocommerce-public.js 191
public/class-ultimate-wishlist-for-woocommerce-public.php 201
includes/class-ultimate-wishlist-for-woocommerce-renderer.php  218 274

**Using different package and subpackage-**
includes/class-ultimate-wishlist-for-woocommerce-crud-manager.php 
includes/class-ultimate-wishlist-for-woocommerce-helper.php
includes/class-ultimate-wishlist-for-woocommerce-shortcode-manager.php
includes/class-ultimate-wishlist-for-woocommerce-template-manager.php
includes/class-ultimate-wishlist-for-woocommerce-renderer.php 
public/partials/ultimate-wishlist-for-woocommerce-shortcode-view.php

Please make sure the prefixes of all functions is the same.

**Avoid touching the database directly by $wpdb->insert**
includes/class-ultimate-wishlist-for-woocommerce-crud-manager.php

**PHPCS Issues-**
[ultimate-wishlist-for-woocommerce.docx](https://github.com/Makewebbetter/ultimate-wishlist-for-woocommerce/files/6869082/ultimate-wishlist-for-woocommerce.docx)

**Comment by AnuraktSachan-CEDCOSS** [comment]
PHPCS Issues:-
[ultimate-wishlist-for-woocommerce.docx](https://github.com/Makewebbetter/ultimate-wishlist-for-woocommerce/files/6910718/ultimate-wishlist-for-woocommerce.docx)

**Comment by Stuti-Cedcoss** [comment]
$wpdb-&gt;prepare() please ignore this issue as the parameter passed is the value stored and then passed in the $wpdb-&gt;result()

**Comment by AnuraktSachan-CEDCOSS** [comment]
PHPCS Issues:-
[ultimate-wishlist-for-woocommerce.docx](https://github.com/Makewebbetter/ultimate-wishlist-for-woocommerce/files/6948465/ultimate-wishlist-for-woocommerce.docx)

**Comment by AnuraktSachan-CEDCOSS** [comment]
Update it. 

 * WP Tested up to :        5.8.0
 * WC tested up to:         5.5.2

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
PHPCS Issues:-
[ultimate-wishlist-for-woocommerce.docx](https://github.com/Makewebbetter/ultimate-wishlist-for-woocommerce/files/6962416/ultimate-wishlist-for-woocommerce.docx)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
