### ISSUE TITLE
Language Issue

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#65]
**Bug Name -** Language Issue
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.5.2
**WordPress Version -** 5.8
**PHP Version -** 8.0.0
**Plugin Version -** 1.0.2
**Description -**

![image](https://user-images.githubusercontent.com/76723393/127745434-457a6907-4085-4f6c-9146-d8051aba8684.png)

![image](https://user-images.githubusercontent.com/76723393/127745444-44ac76dc-bc00-47e4-86cb-9ceba30a078d.png)

![image](https://user-images.githubusercontent.com/76723393/127745448-42b6bad6-16d0-4925-9cf6-da67400e0363.png)

![image](https://user-images.githubusercontent.com/76723393/127745461-cc273291-de53-44e4-9fc2-7951c5df9244.png)

![image](https://user-images.githubusercontent.com/76723393/127745519-e4863729-71ec-49b5-9340-59b25d58382b.png)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
