### ISSUE TITLE
Deactivation form Issue.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#66]
**Bug Name -** Deactivation form Issue.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.5.2
**WordPress Version -** 5.8
**PHP Version -** 8.0.0
**Plugin Version -** 1.0.2
**Description -**

Deactivation form data are not sending.

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
Not fixed, Please check

**Comment by Stuti-Cedcoss** [comment]
It is fixed.Please check the mail id you entered as the admin mail id it should be a valid mail id for successfully sending the mail.

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
