### ISSUE TITLE
Design issues.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#67]
**Bug Name -** Design issues.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.5.2
**WordPress Version -** 5.8
**PHP Version -** 8.0.0
**Plugin Version -** 1.0.2
**Description -**
![image](https://user-images.githubusercontent.com/76723393/129658719-d5c7911c-c1bc-40c3-b9c0-45a4ebfccca6.png)
![image](https://user-images.githubusercontent.com/76723393/129658737-105bfdf9-a5e7-4b85-b941-cd6917618693.png)
![image](https://user-images.githubusercontent.com/76723393/129658759-bce55ef6-443f-49d7-9a45-70be678af717.png)
![image](https://user-images.githubusercontent.com/76723393/129658771-0b271166-6a64-4184-abef-995cbd5ae74f.png)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
