### ISSUE TITLE
Fatal Error [ Compatibility with MWB Quick View for WooCommerce ]

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#68]
**Bug Name -**  Fatal Error [ Compatibility with MWB Quick View for WooCommerce ]
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.6.0
**WordPress Version -** 5.8.0
**Plugin Version -** 1.0.3
**Description -**

In quick view when you exclude all categories then on the wishlist page Fatal Error displayed.

![image](https://user-images.githubusercontent.com/76723393/132575553-9a8fac01-140c-4486-9f1c-944a6871cd27.png)

![image](https://user-images.githubusercontent.com/76723393/132575445-0210d609-0f54-4ead-8aed-1ec156cf5231.png)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
