### ISSUE TITLE
In multi-site wishlist have some issue. 

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#69]
**Bug Name -**  In multi-site wishlist have some issue. 
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.6.0
**WordPress Version -** 5.8.0
**Plugin Version -** 1.0.3
**Description -**

![image](https://user-images.githubusercontent.com/76723393/132992043-aa15943b-cbdc-453c-920d-52a0b7f0175e.png)

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
