### ISSUE TITLE
Select cursor is not coming fine.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#70]
WordPress version: 5.8.1
WooCommerce version: 5.6.0
Compatible: Membership For WooCommerce
Area Path: Store-end-> Wishlist
Version: 1.0.3
Description: Select cursor is not coming fine. The normal select cursor should come while the Text select cursor is coming over the cross button.
![1631891662929](https://user-images.githubusercontent.com/76723329/133807864-fccebcc2-bde6-499c-8ec2-fc5106638445.JPEG)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
