### ISSUE TITLE
Warning Notice.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#71]
**Bug Name -** Warning Notice.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.7.0
**WordPress Version -** 5.8.0
**Plugin Version -** 1.0.2
**Description -**

![image](https://user-images.githubusercontent.com/76723393/134456418-fc440b71-14c5-4776-baca-01197555e0ff.png)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
generate a new similar issue.

![image](https://user-images.githubusercontent.com/76723393/134865347-bef99e8a-2bc0-4934-b55b-996f3101603d.png)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
OK
