### ISSUE TITLE
QA Issues.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#72]
**Bug Name -** QA Issues.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.7.1
**WordPress Version -** 5.8.1
**Plugin Version -** 1.0.3
**Description -**

Commented Code-
public/css/ultimate-wishlist-for-woocommerce-public.css  327

Text Domain Issue.
ultimate-wishlist-for-woocommerce/public/class-ultimate-wishlist-for-woocommerce-public.php 262 

$wpdb->insert 
includes/class-ultimate-wishlist-for-woocommerce-crud-manager.php

All Prefix of functions is not the same.

PHPCS Issues

[ultimate-wishlist-for-woocommerce.docx](https://github.com/Makewebbetter/ultimate-wishlist-for-woocommerce/files/7255188/ultimate-wishlist-for-woocommerce.docx)

**Comment by Stuti-Cedcoss** [comment]
Fixed
$wpdb->prepare() please ignore this issue as the parameter passed is the value stored and then passed in the $wpdb->result()

**Comment by AnuraktSachan-CEDCOSS** [comment]
OK
