### ISSUE TITLE
QA Issues.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#74]
**Bug Name -** QA Issues.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.9.0
**WordPress Version -** 5.8.2
**Plugin Version -** 1.0.4
**Description -**

WP Tested up to :        5.8.1
WC tested up to:         5.8.0

PHPCS Issues-
[ultimate-wishlist-for-woocommerce.docx](https://github.com/Makewebbetter/ultimate-wishlist-for-woocommerce/files/7531608/ultimate-wishlist-for-woocommerce.docx)

**Comment by Stuti-Cedcoss** [comment]
All issues fixed 
$wpdb->prepare() please ignore this issue as the parameter passed is the value stored and then passed in the $wpdb->result()

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
